CREATE TABLE categories (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  UUID binary(16) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UK_uuid (UUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tasks (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  UUID binary(16) NOT NULL,
  CATEGORY_ID binary(16) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY CATEGORY_ID (CATEGORY_ID),
  FOREIGN KEY (CATEGORY_ID) REFERENCES categories(UUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
